<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<title>Julian's Home Page</title>';
echo '<meta charset="utf-8">';
echo '</head>';
echo '<!--MISM 3320: LAB 5 Dorise 2/26/2021-->';
echo '<style>';
echo 'body {';
echo 'background-color: black;';
echo 'color: white;';
echo 'font-family: Georgia;';
echo '"Verdana",';
echo 'serif;';
echo 'background-image: url(https://www.publicdomainpictures.net/pictures/190000/velka/usa-city-lights.jpg);';
echo '}';
echo '';
echo 'h1 {';
echo 'background-color: #FFFFFF;';
echo 'color: #000000;';
echo 'font-family: Ariel, Verdana, sans-serif;';
echo '}';
echo '';
echo 'h2 {';
echo 'background-color: #CCCCCC;';
echo 'color: #000000;';
echo 'font-family: Ariel, Verdana, sans-serif;';
echo '}';
echo '';
echo '.new {';
echo 'color: blue;';
echo 'font-style: italic font-weight:bold;';
echo '}';
echo '';
echo '.feature {';
echo 'color: green;';
echo '}';
echo '';
echo '<li class="new">My hope is to leverage my education in technology to help bring about change and drive innovation throughout the world.Traveling</li>';
echo '</style>';
echo '';
echo '<head>';
echo '';
echo '<body>';
echo '<h1 style="text-align:center;">';
echo '<b>Julian Dorise Web Page</b>';
echo '</h1>';
echo '<div><a href="index.html">Home</a> <a href="services.html">Services</a> <a href="contact.html">Contact</a></div>';
echo '<hr>';
echo '<p><b><i> My name is Julian Dorise, I am a native Ohioian, who has relocated to Dallas, Texas where I've lived for';
echo 'over 12 years now.';
echo 'I'm currently a college student enrolled at Dallas Baptist University, majoring in Systems Technology';
echo 'and Information Management.';
echo 'This website page is being lauched to introduce myself and shed some insight into some of my interests';
echo 'as we work through this course.</i></b></p>';
echo '';
echo '<hr>';
echo '';
echo '<h2>Drive to Educate and Inspire</h2>';
echo '<p> I'm learning Web Design, as a way to further develop my skills in design principles, HTML, and CSS.</P>';
echo '<p>';
echo '<font size="-1" color="darkblue">';
echo 'My hope is to leverage my education in technology to help bring about change and drive innovation throughout';
echo 'the world.';
echo '</font>';
echo '</p>';
echo '<blockquote>';
echo '"It's not a faith in technology. It's faith in people." - Steve Jobs';
echo '</blockquote>';
echo '<h3>What I enjoy</h3>';
echo '<ol>';
echo '<li>Reading</li>';
echo '<li>Design</li>';
echo '<li>Traveling</li>';
echo '</ol>';
echo '<h4>How I'm described</h4>';
echo '<ul>';
echo '<li>Compassionate</li>';
echo '<li>Ambitious</li>';
echo '<li>Courteous</li>';
echo '<li>Amiable</li>';
echo '<li>passionate</li>';
echo '</ul>';
echo '<h5>My favorite Websites</h5>';
echo '<a href="http://forbes,com/innovation.com">Forbes Tech</a>';
echo '<a href="http://TechCrunch.com"> Tech Crunch Informational</a>';
echo '<h6>Contact us</h6>';
echo '<ul>';
echo '<li class="feature"> Questions?';
echo '<a href="mailto:jdorise7636@mail.dbu.edu">Email Webmaster</a>';
echo '</li>';
echo '';
echo '<a href="http://dbu.edu"><img src="images/Dallas Baptist University.png" width="64" height="64"';
echo 'alt="Dallas Baptist University" /></a>';
echo '<hr>';
echo '<div id="footer"><small>Copyright &copy; 2021 Julian Dorise</small></div>';
echo '</body>';
echo '';
echo '</html>';
?>